name: Elixir GitHub Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
            version-file: .tool-versions
            version-type: strict

      - run: mix deps.get
      - run: mix compile --all-warnings --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test